import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Rang Mahal",
  description: "Generated by create next app",
  icons: ["/logo.svg"],
};
const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <main className="min-h-screen">
      <Navbar />
      {children}
      <Footer />
      <Toaster />
    </main>
  );
};
export default Layout;
